import type { Resume } from "@/types/resume";

export type Lang = "en" | "es";

/** Escape Typst markup-mode special characters inside [...] content blocks. */
function esc(s: string): string {
  return s
    .replace(/#/g, "\\#")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/@/g, "\\@")
    .replace(/</g, "\\<")
    .replace(/>/g, "\\>");
}

/** Escape for Typst string literals inside "..." in code mode. */
function escStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function formatDate(date: string): string {
  if (!date) return "";
  const [year, month] = date.split("-");
  if (!month) return year ?? "";
  const MONTHS = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  return `${MONTHS[parseInt(month) - 1] ?? ""} ${year}`;
}

function dateRange(start: string, end: string, presentLabel: string): string {
  const s = formatDate(start);
  const e = end ? formatDate(end) : presentLabel;
  return s ? `${s}–${e}` : e;
}

const LABELS = {
  en: {
    curriculum: "Curriculum Vitae",
    experience: "Professional Experience",
    education: "Education",
    courses: "Courses & Certifications",
    projects: "Projects",
    present: "present",
  },
  es: {
    curriculum: "Currículum",
    experience: "Experiencia profesional",
    education: "Formación académica",
    courses: "Cursos y certificaciones",
    projects: "Proyectos",
    present: "actualidad",
  },
};

export function generateMomoTypst(resume: Resume, lang: Lang = "en"): string {
  const labels = LABELS[lang];
  const { personalInfo: p, education, experience, courses, projects } = resume;

  const fullName = `${p.firstName} ${p.lastName}`.trim();
  const phone = `${p.phoneCode} ${p.phoneNumber}`.trim();
  const location = [p.city, p.country].filter(Boolean).join(", ");
  const contactItems = [p.email, phone || null, location || null].filter(
    Boolean,
  ) as string[];

  const lines: string[] = [];

  // ── Preamble ─────────────────────────────────────────────────────────────
  lines.push(
    `// Auto-generated by CV Helper — Momo template`,
    `#set page(margin: (x: 2.5cm, y: 2.5cm))`,
    `#set text(font: "Libertinus Serif", size: 11pt)`,
    `#let accent = rgb("#4C8C7A")`,
    ``,
    `#let section(title) = [`,
    `  #v(0.8em)`,
    `  #grid(`,
    `    columns: (5cm, auto),`,
    `    column-gutter: 0.8em,`,
    `    align: horizon,`,
    `    line(length: 100%, stroke: (paint: accent, thickness: 2pt)),`,
    `    text(size: 14pt, fill: accent)[#title],`,
    `  )`,
    `  #v(0.3em)`,
    `]`,
    ``,
    `#let entry(date, body) = [`,
    `  #grid(`,
    `    columns: (3cm, 1fr),`,
    `    column-gutter: 1em,`,
    `    [#text(weight: "regular")[#date]],`,
    `    [#body]`,
    `  )`,
    `  #v(0.3em)`,
    `]`,
    ``,
  );

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(
    `#grid(`,
    `  columns: (1fr, 1fr),`,
    `  [`,
    `    #text(size: 28pt, weight: "bold")[${esc(fullName)}]`,
    `    #v(0.4em)`,
    `    #text(size: 18pt, fill: gray)[${esc(labels.curriculum)}]`,
    `  ],`,
    `  [`,
    `    #align(right)[`,
    ...contactItems.map((item, i) =>
      i < contactItems.length - 1
        ? `      ${esc(item)} \\`
        : `      ${esc(item)}`,
    ),
    `    ]`,
    `  ]`,
    `)`,
    `#v(1.5em)`,
  );

  // ── Summary ───────────────────────────────────────────────────────────────
  if (p.summary?.trim()) {
    lines.push(``, esc(p.summary.trim()), `#v(0.5em)`);
  }

  // ── Experience ────────────────────────────────────────────────────────────
  if (experience.length > 0) {
    lines.push(``, `#section("${escStr(labels.experience)}")`);
    for (const exp of experience) {
      const date = escStr(dateRange(exp.startDate, exp.endDate, labels.present));
      lines.push(``, `#entry("${date}", [`);
      lines.push(`  *${esc(exp.title)}*, ${esc(exp.company)}`);
      if (exp.description?.trim()) lines.push(`  ${esc(exp.description.trim())}`);
      lines.push(`])`);
    }
  }

  // ── Education ─────────────────────────────────────────────────────────────
  if (education.length > 0) {
    lines.push(``, `#section("${escStr(labels.education)}")`);
    for (const edu of education) {
      const date = escStr(dateRange(edu.startDate, edu.endDate, labels.present));
      const degreeField = [edu.degree, edu.field].filter(Boolean).join(" in ");
      lines.push(``, `#entry("${date}", [`);
      lines.push(`  *${esc(degreeField)}*, ${esc(edu.institution)}`);
      lines.push(`])`);
    }
  }

  // ── Courses ───────────────────────────────────────────────────────────────
  if (courses.length > 0) {
    lines.push(``, `#section("${escStr(labels.courses)}")`);
    for (const course of courses) {
      const date = escStr(formatDate(course.date));
      lines.push(``, `#entry("${date}", [`);
      lines.push(`  *${esc(course.name)}*, ${esc(course.provider)}`);
      lines.push(`])`);
    }
  }

  // ── Projects ──────────────────────────────────────────────────────────────
  if (projects.length > 0) {
    lines.push(``, `#section("${escStr(labels.projects)}")`);
    for (const proj of projects) {
      const nameEsc = esc(proj.name);
      const urlEsc = proj.url ? esc(proj.url) : "";
      const nameAndUrl = urlEsc ? `*${nameEsc}* — ${urlEsc}` : `*${nameEsc}*`;
      lines.push(``, `#entry("", [`);
      lines.push(`  ${nameAndUrl}`);
      if (proj.description?.trim()) lines.push(`  ${esc(proj.description.trim())}`);
      lines.push(`])`);
    }
  }

  return lines.join("\n");
}
